# Generated by Django 4.2.11 on 2026-06-07 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paroquia', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('alimento', 'Alimento'), ('roupa', 'Roupa'), ('medicamento', 'Medicamento'), ('outro', 'Outro')], max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('unidade', models.CharField(default='unidade', max_length=50)),
                ('validade', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Estoque',
                'verbose_name_plural': 'Itens do Estoque',
                'ordering': ['validade', 'nome'],
            },
        ),
    ]
